services:
  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      MONGO_URI: mongodb://mongo:27017/chat_db
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ALGORITHM: HS256
      PORT: 5000
    depends_on:
      - mongo
    ports:
      - "5003:5000"   # host:container
    command: ["gunicorn", "--bind", "0.0.0.0:5000", "app:app", "--workers", "1", "--threads", "8", "--timeout", "120"]

  # Optional: token minting helper for dev
  auth:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      MONGO_URI: mongodb://mongo:27017/chat_db
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ALGORITHM: HS256
      PORT: 5000
    depends_on:
      - mongo
    ports:
      - "5001:5000"
    command: ["gunicorn", "--bind", "0.0.0.0:5000", "auth_app:auth_app", "--workers", "1", "--threads", "4", "--timeout", "60"]

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        # IMPORTANT: bake same-origin API base into the bundle
        VITE_BACKEND_URL: /api
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  mongo_data:
